
import type { Metadata } from "next";
import { Montserrat, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Poppins } from "next/font/google";
const poppins = Poppins({ subsets: ["latin"], weight: ["400", "700", "900"], variable: "--font-poppins" });
import { Providers } from "@/components/snackProvider/ProviderSnack";
import CartMenu from "@/components/common/CartMenu";
import Header from "@/components/header/Header";
import FooterTop from "@/components/foooter/FooterTop";
import Footer from "@/components/foooter/Footer";
import { usePathname } from "next/navigation";

// تحميل الخطوط وإعداد متغيرات CSS
const montserrat = Montserrat({ subsets: ["latin"], variable: "--font-montserrat" });
const geist = Geist({ subsets: ["latin"], variable: "--font-geist" });
const geistMono = Geist_Mono({ subsets: ["latin"], variable: "--font-geist-mono" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {

  return (
    <html lang="en" className={poppins.className}>
      <body className="antialiased" >
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}