
import type { Metadata } from "next";
import { Montserrat, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Poppins } from "next/font/google";
const poppins = Poppins({ subsets: ["latin"], weight: ["400", "700", "900"], variable: "--font-poppins" });
import { Providers } from "@/components/snackProvider/ProviderSnack";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {

  return (
    <html lang="ar" className={poppins.className}>
      <body className="antialiased" >
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}